
export const metadata =[
    {
        id: Date.now()+1,
        name: 'Employee1',
        empid: 1001,
        position: 'Software Trainee',
        gender: 'Male',
        percent: 100,
        color:'success',
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
    {
        id: Date.now()+2,
        name: 'Employee2',
        empid: 1002,
        position: 'Software Developer',
        gender: 'Female',
        color:'success',
        percent: 100,
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
    {
        id: Date.now()+3,
        name: 'Employee3',
        empid: 1003,
        position: 'Software Trainee',
        gender: 'Male',
        color:'success',
        percent: 100,
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
    {
        id: Date.now()+4,
        name: 'Employee4',
        empid: 1004,
        position: 'Software Developer',
        gender: 'Female',
        color:'success',
        percent: 100,
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
    {
        id: Date.now()+5,
        name: 'Employee5',
        empid: 1005,
        position: 'Software Trainee',
        gender: 'Male',
        color:'success',
        percent: 100,
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
    {
        id: Date.now()+6,
        name: 'Employee6',
        empid: 1006,
        position: 'Software Developer',
        gender: 'Female',
        color:'success',
        percent: 100,
        totaltasks: 0,
        pending: 0,
        completed: 0,
        workhours: "08:00" ,
    },
]